### ISSUE TITLE
Text overlapping

### ISSUE THREAD

**Issue by Adaptivity** [AEnterprise/Eureka#21]
http://i.imgur.com/n6eK7Js.jpg Is it possible to do something with it? It applies to all researches.

**Comment by AEnterprise** [comment]
yeah, probably one of the few hardcoded lines, but it'll have to wait sadly, i'm first gona finish the BCA 2.0 update, then i plan on doing a pretty major rewrite on eureka, moving localizations to seperate files and probably look intro adding images and such

**Comment by AEnterprise** [comment]
shouldn't be an issue in the next eureka version anymore
