### ISSUE TITLE
Multiple blocks/items with one research.

### ISSUE THREAD

**Issue by Dominance** [AEnterprise/Eureka#22]
Looking for a wildcard approach such as minecraft:"*" to tie ether the entire mod or for instance minecraft:machines:"*" for meta data wildcard.

**Comment by AEnterprise** [comment]
not sure if it's possible to use it on an entire mod at once but it sure would be possible to make it to block multiple things with the same research

**Comment by AEnterprise** [comment]
this is now possible with the new eureka
