### ISSUE TITLE
Config option to disable book on respawn

### ISSUE THREAD

**Issue by Adaptivity** [AEnterprise/Eureka#26]
Would be cool to see config option for disabling book on respawn.

**Comment by AEnterprise** [comment]
should be easy enough to make

**Comment by AEnterprise** [comment]
you only get the book once

**Comment by Adaptivity** [comment]
I mean an option to not get book at all. You should craft it instead.

**Comment by AEnterprise** [comment]
oh like that, sorry misunderstood it

**Comment by AEnterprise** [comment]
added

**Comment by Adaptivity** [comment]
Thanks. You still not localized ChatComponentText in MessageResearchFinished.java, just a reminder.
