### ISSUE TITLE
Crash when starting world

### ISSUE THREAD

**Issue by erkro1** [AEnterprise/Eureka#28]
I get this crash: java.lang.NoClassDefFoundError: eureka/api/EurekaAPI

Full crash log:
http://pastebin.com/066MkqeX

I'm using Buildcraft Additions #124

**Comment by BigXplosion** [comment]
what version of Eureka have you installed?

**Comment by BigXplosion** [comment]
The problem is that you use a version of BCA which is using the new Eureka. The new Version of Eureka is currently only available for testers. So what I recommend is downgrading BCA to [build 111](http://ci.tterrag.com/job/Buildcraft-Additions/111/) or even to the latest stable on curse.

**Comment by erkro1** [comment]
Ah alright that might cause it, thanks for the help!

**Comment by AEnterprise** [comment]
yep that's the issue here, the new eureka isn't done yet so no relase of that yet
