### ISSUE TITLE
Server Side Crash when opening engineering book.

### ISSUE THREAD

**Issue by mindcloud69** [AEnterprise/Eureka#31]
https://gist.github.com/f3c9d4182e578a6e751e.git

**Comment by iTitus** [comment]
Does this happen with Forge 10.13.2.1291?

**Comment by iTitus** [comment]
Working link: https://gist.github.com/mindcloud69/f3c9d4182e578a6e751e

**Comment by mindcloud69** [comment]
Yes same issue
