### ISSUE TITLE
"EUREKA!" Spam In Chat

### ISSUE THREAD

**Issue by fcpwiz** [AEnterprise/Eureka#32]
After updating to 3.0, the text "EUREKA!" spams the chat about every 20 seconds.

**Comment by O13SC3N3** [comment]
Yep, problem still exist.

**Comment by fcpwiz** [comment]
Is this actually going to get "fixed"?

**Comment by AEnterprise** [comment]
@fcpwiz what do you mean by 'in chat'? in your in game chat or in the game console?

also why are you asking if this is gona actually get fixed? of course i'm gona fix it but you only opened this issue 6 hours ago when i was sleeping, i didn't had the chanse to reply yet

**Comment by fcpwiz** [comment]
Yeah this only happens in the chat. It doesn't show up in the console.

**Comment by AEnterprise** [comment]
you sure you have eureka 3.0 downloaded from curseforge?

**Comment by fcpwiz** [comment]
Yes

**Comment by fcpwiz** [comment]
I'm using Eureka-1.7.10-3.0.jar

**Comment by AEnterprise** [comment]
so it's every 20 sec? you sure it's 20 sec and not each time you do something?

**Comment by fcpwiz** [comment]
Well it kinda varies. But it mostly pops up after I say something in chat.

**Comment by fcpwiz** [comment]
It's actually very random. http://i.imgur.com/KSWUhpT.png

**Comment by fcpwiz** [comment]
Oh wait. Every time I hit "E" it prints "EUREKA!"

**Comment by AEnterprise** [comment]
@fcpwiz now that makes more sense, now i know what it is i can fix it

**Comment by fcpwiz** [comment]
Ok good

**Comment by fcpwiz** [comment]
Also, when you kill an entity it says "EUREKA!" as well.

**Comment by fcpwiz** [comment]
And, when you pick up the mob drops. Wow.

**Comment by fcpwiz** [comment]
Oh god, and it only shows up when you kill a hostile mob. Not a peaceful mob.

**Comment by fcpwiz** [comment]
After further examination, it looks like "EUREKA!" Shows up when:

- You open your inventory
- You pick up/add items to your inventory that weren't originally there
- You kill a non-minecraft mob

**Comment by jermangarc** [comment]
Yup got this same issue as well, every time I open up my inventory.

**Comment by fcpwiz** [comment]
@jermangarc Yeah. Hope there will be a fix soon. All my players on my server are going haywire about if. Haha

**Comment by AEnterprise** [comment]
could you guys try in singleplayer and see if the issue is also pressent then?

**Comment by fcpwiz** [comment]
Looks like it doesn't occur in single player. Odd.

**Comment by AEnterprise** [comment]
just what i thought, the problem lies in the research syncing code, in singleplayer client and server are the same so some things work then and not in multiplayer

**Comment by fcpwiz** [comment]
Ok. When are we expecting a fix? :)

**Comment by AEnterprise** [comment]
will do my best to fix this over the weekend and do a release

**Comment by fcpwiz** [comment]
great! thanks man

**Comment by fcpwiz** [comment]
Awesome! Thanks for the fix! When are you planning on releasing this version?

**Comment by AEnterprise** [comment]
today or tomorow, got a few other bugs to squach

**Comment by fcpwiz** [comment]
Ok. Now looking at the changes you made, I can't seem to find the line that prints "EUREKA!" Where is it?

**Comment by AEnterprise** [comment]
it is here: https://github.com/AEnterprise/Eureka/commit/04b30b896a5ebdbdb3d75fffb0e297c8adb54793#diff-0729800cbb7ac429bfe41f3510226d45R49

the issue was that the server was trying to send the message but errored when trying to localize the title

**Comment by fcpwiz** [comment]
I mean the old line that you had to delete to remove it from saying "EUREKA!"

**Comment by AEnterprise** [comment]
the lines linked to replace that, the old line was removed and instead it sends a message to the client telling it to print out the message

**Comment by fcpwiz** [comment]
ah ok! nice work!

**Comment by AEnterprise** [comment]
eureka 3.0.1 released

**Comment by fcpwiz** [comment]
Awesome! Where can I download it? It's not showing up on curse forge for me.

**Comment by AEnterprise** [comment]
check on curseforge again in a few mins, uploaded it but curse hasn't aproved the file yet

**Comment by AEnterprise** [comment]
@fcpwiz file is available now
