### ISSUE TITLE
Eureka spam in chat and crash after attempting to open book

### ISSUE THREAD

**Issue by jermangarc** [AEnterprise/Eureka#33]
Here is the report. Using Eureka 3.0 downloaded from Curseforge. The crash happened on server. In single player world it does not crash but the pages are empty and the book is not working as it used to. Will be posting pictures as soon as I get them on dropbox.

EDIT: I digress a bit. The book seams to be working fine on the last four tabs, it's only the first two tabs that are empty, not sure if this was intentional. 
https://www.dropbox.com/s/4yv78k37rovcmvk/2015-04-02_15.55.49.png?dl=0
https://www.dropbox.com/s/y7sotguw1fd3ytc/2015-04-02_15.55.51.png?dl=0

Crashlog:http://pastebin.com/iJNjCFaq

**Comment by AEnterprise** [comment]
hmm, could you check the eureka config folder? if there are any json files in the 'categories' folder dele them (if you didn't put them there) that should make the second empty category go away, the first category is empty intentionally

**Comment by Xisdibik** [comment]
I checked the 'categories' folder for jsons and there were 0 on both my server and client.  I get the crash when I open the book, I also play on a server (my server).  Same crash log as the one pasted by jermangarc.
