### ISSUE TITLE
Eureka 3.0.1 server issue

### ISSUE THREAD

**Issue by sebs08** [AEnterprise/Eureka#34]
Hi,
during the last days I tried to get the newsest Eureka (3.0.1) and BcA updates running.
Unfortunately I always get this error message when I start the forge server:
http://pastebin.com/S1yNuvTM

I would be thankful if you could help me with this one. 
Btw I really enjoy playing your mods. :)
Greetings Seb

**Comment by AEnterprise** [comment]
oh i see, your server is running but doesn't have read rights so eureka is trying to make it's config folders, that fails but doesn't crash it (wrote protection for that) but i forgot to protect against crashes when trying to read out files in those folders

for now a workaround would be to go intro the config folder, make a folder called Eureka.
in there make 3 more folders: Categories, Keys and Localizations
