### ISSUE TITLE
[Eureka 3.01] I can not unlock the Portable Laser

### ISSUE THREAD

**Issue by Be-Cool-Man** [AEnterprise/Eureka#35]
I crafting a BC-Laser and place it on an Kinesis-Pipe. But the counter in the Engeneering Diary stands always by 0/4.

---
Installed Mods:

appliedenergistics2-rv2-beta-28
bamsgrave-1.7.2-1.4.2_01
bspkrsCore-universal-6.16
buildcraft-6.4.8
buildcraft-compat-6.4.2
BuildcraftAdditions-1.7.10-2.1.1
ChickenChunks-1.7.10-1.3.4.19-universal
CodeChickenCore-1.7.10-1.0.4.35-universal (1)
CodeChickenLib-1.7.10-1.1.3.127-universal
EnderIO-1.7.10-2.2.8.344
EnderStorage-1.7.10-1.4.5.29-universal
Eureka-1.7.10-3.0.1
extrautilities-1.2.2
ForgeMultipart-1.7.10-1.1.1.326-universal
NotEnoughItems-1.7.10-1.0.4.94-universal
OpenEye-0.6-1.7.10
QuarryPlus-1.7.10-2.1.0
simplefluidtanks-1.7.10-1.2.0.5
Telepads-1.7.2_1.7
Treecapitator-universal-2.0.4
Waila-1.5.10_1.7.10

**Comment by AEnterprise** [comment]
fixed
